version: "3.8"
services: 
  anonymizer:
    build: .
    image: &img anonymizer 
    command: python -m face_anonymizer.server --port=80 --interface=0.0.0.0
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    networks:
      anonymizer_net:
        ipv4_address: 172.25.0.2

networks:
  anonymizer_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/16
          gateway: 172.25.0.1